import './globals.css'
import Sidebar from '@/components/Sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className='bg-slate-50 dark:bg-gray-950 text-white'>
        <div className="flex gap-4">
          <Sidebar />
          <div className="p-4 sm:ml-64 w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
